name: Run Rspec Tests

on:
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-18.04

    services:
      postgres:
        image: postgres:10.11
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v1

    - name: Cache Ruby
      uses: actions/cache@preview
      id: cache
      with:
        path: ~/local/rubies
        key: ruby-2.6.4

    - name: Set up Ruby 2.6.4
      uses: clupprich/ruby-build-action@master
      id: ruby
      with:
        ruby-version: 2.6.4
        cache-available: ${{ steps.cache.outputs.cache-hit == 'true' }}

    - name: Print ruby version
      run: ${{ steps.ruby.outputs.ruby-path }} --version

    - name: Install PostgreSQL 10
      run: |
        sudo apt-get -yqq install libpq-dev

    - name: Setup Database
      env:
        PGHOST: localhost
        PGUSER: postgres
        RAILS_ENV: test
      run: |
        gem install bundler -v 2.1.4
        bundle install --jobs 4 --retry 3
        bin/rails db:create db:migrate db:seed

    - name: Build and test with rspec
      env:
        PGHOST: localhost
        PGUSER: postgres
        RAILS_ENV: test
      run: |
        gem install bundler -v 2.1.4
        bundle install --jobs 4 --retry 3
        rm -rf bin/webpack*
        rails webpacker:install
        RAILS_ENV=test bundle exec rails webpacker:compile
        bundle exec rspec spec
